-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.40.9 as of 10/11/2024 7:02 AM
-- Source Configuration: BAT_Forms
-- Objects scripted:
--   Strings: _IEM_ssPaid=P, AuditReportTextCaption, C(SalesTaxTemplateStatic),
--      Ending Date, EndingDateIsOutofRange, Exclude Excel Rows,
--      f_IEM_AssignSiteShipping, f_IEM_CoItemUpdateOrderQty,
--      f_IEM_CoItemUpdateOrderQtySp, f_IEM_JobConfigImport,
--      f_IEM_JobMaterialRelease, f_IEM_Load_Table,
--      f_IEM_Scheduler_OperationsManagement, f_IEM_Scheduler_SiteScheduler,
--      f_IEM_SchedulingGroupSetup, f_IEM_WCScheduleView,
--      f_MassEngineeringDrawingApprovals, fAccountsReceivableAgingReport(IEM),
--      fBookingsReport (IEM), fCustomerStatementsReport (IEM), fDatabaseAudit,
--      fIEMCombinedTransferOrderShip/Ship_IEM, fImportCurrencyConversion_IEM,
--      fJobMaterialChange_IEM, fJobOrderReceiptProcess_IEM, fJobPickList (IEM),
--      fJobRelease_IEM, fOrderAcknowledgmentReport, fOrderInvoicingCM,
--      fPurchaseOrderReportIEM, fReferenceDate(Optional), fReportType,
--      fSalesByProductType, fSalesTaxReportIEM, fShippingReport, fStartingDate,
--      fTaxCollectedOnSales, fTaxPaidOnPurchases,
--      Include Orders Shipped Complete, Include Shipped, IncludePrice,
--      m%LIsOutofRange, mInvoiceReprintExcess, mIsNotAValid, mQ=CmdQueryNoYes,
--      mQ=CommMult_IEM, mQ=DeleteLinkedTOLineYesNo_IEM,
--      mQ=PoCostLessThanVendorMinYesNo_IEM, mQ=UpdateLinesYesNo_IEM,
--      mW=ChangeVendorHasMinOk_IEM, mW=PoCostLessThanVendorMinOk_IEM,
--      mW=VendorHasMinOk_IEM, PleaseWork, Queries (IEM), Resale Certificate,
--      sAdd/DelQty_IEM, sAge/Days, sAge/Hrs, sAge/Mins, sAssemblyStartDate_IEM,
--      sAssignSite_IEM, sBin_IEM, sBucket_IEM, sBulk_IEM, sCareOf_IEM,
--      sChangeCompleteStatus_IEM, sChangeOperations_IEM,
--      sCommissionMultiplier_IEM, sCommissionMultiplier1_IEM,
--      sCommissionMultiplier2_IEM, sCommissionMultiplier3_IEM,
--      sCommissionMultiplier4_IEM, sConcurrentGroups_IEM, sConcurrentID_IEM,
--      sCoQtyRemaining_IEM, sCoShipSite_IEM, sCreateSessionDateIEM,
--      sCustomerRequestedShipDate_IEM, sDay/Week/Month_IEM, sDB_IEM,
--      sDefaultMaterialCushion_IEM, sDeselectAll,
--      sDoNotAddFreightAtTimeOfShipment_IEM, sEst/ActHrs_IEM,
--      sEstimateOperationScheduled_IEM, sExcel, sExpandAllProductTypes,
--      sFirstOpSubOp_IEM, sFreightAllowed_IEM, sGroupMechanical_IEM,
--      sHardware_IEM, sHours/PlannedPersonnel_IEM, sHrsThreshold_IEM,
--      sIEM_AssignSite, sIEM_ContactEmail, sIEM_ImportLabor, sIEM_ImportQuote,
--      sIEM_PerformEquoteWriteBacks, sIEMCustom_IEM, sIEMCustomParms_IEM,
--      sIEMDrawApprDate, sIEMEngLeadTime, sIEMEngSubmittal,
--      sIEMImportFisiMaterial, sIEMJobName, sIEMProdLeadTime,
--      sIEMSchedLoadComplete_IEM, sIncludeComplete_IEM, sIncludeShipped,
--      sIneligibleCustomer_IEM, sInternalUseOnly, sJobReleaseAutomation_IEM,
--      sLastSubOp_IEM, sLastUseSessionDateIEM, sLinesExist_IEM,
--      sLoadComplete_IEM, sLoadDays_IEM, sLoadNewJobs_IEM,
--      sMaterialCushionDays_IEM, sMechanicalActHrs_IEM, sMechanicalGroup_IEM,
--      sMechanicalSubTotal_IEM, sMechNumWorkers_IEM, sMFGMatlType_IEM,
--      sMfgTypeSite_IEM, sMinimumPOAmount_IEM, sNewSiteAssignment_IEM,
--      sNumEmployees_IEM, sNumWorkers_IEM, sOrderAcknowledgment,
--      sOrderVerificationTemplateType=4, sOverPct_IEM, sOverrideCode_IEM,
--      SOVTemplate, sPageBetweenSuffixes, sPrint, sPrintJobName,
--      sPrintLinePrice, sPrintPrice, sPRMA_IEM, sProcessAndPack_IEM,
--      sPromisedShipDate_IEM, sRecordedMarginAllocation_IEM,
--      sReprintPackSlip_IEM, sRequestedSubassemblyArrivalDate_IEM,
--      sResaleCertificate_IEM, sRevenueAllocation_IEM, sSalesperson2_IEM,
--      sSalesperson3_IEM, sSalesperson4_IEM, sSalesTaxReportTemplate,
--      sSalesTaxTemplateType=1, sSalesTaxTemplateType=2, sSchedGroup_IEM,
--      sScheduledShipDate, sScheduleHoursMatrix_IEM, sSchedulerTemplate_IEM,
--      sSchEmployees_IEM, sSchFinalShipDate_IEM, sSchLoadThresholds_IEM,
--      sSchSubAssemblyShipDate_IEM, sSelect, sSelectOrphanedSessionsIEM,
--      sShipAndPack_IEM, sShowInvoiceDetails, sShowSystemUsers,
--      sSiteAssignment_IEM, sSiteConnectionSessions_IEM,
--      sSubassemblyAssignment_IEM, sSubAssemblyTransitTime_IEM, sSubOp_IEM,
--      Starting Date, StartingDateIsOutOfRange, sTemplateType=4,
--      sTransferQtyReceived_IEM, sTransferQtyReq_IEM, sTransferQtyShipped_IEM,
--      sUnderPct_IEM, sWC/NumEmployees_IEM, sWorkdayHours_IEM,
--      sWorkOrderMaterialChange_IEM
-------------------------------------------------------------------------------
DECLARE @FormID INT
DELETE FROM [Strings] WHERE [Name] = N'_IEM_ssPaid=P' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'_IEM_ssPaid=P', N'Paid', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'AuditReportTextCaption' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'AuditReportTextCaption', N'100, 102-200, etc.', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'C(SalesTaxTemplateStatic)' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'C(SalesTaxTemplateStatic)', N'C(Sales Tax Template Static)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'Ending Date' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'Ending Date', N'Ending Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'EndingDateIsOutofRange' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'EndingDateIsOutofRange', N'Ending Date Is Out of Range', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'Exclude Excel Rows' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'Exclude Excel Rows', N'Exclude Excel Rows', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'f_IEM_AssignSiteShipping' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'f_IEM_AssignSiteShipping', N'IEM Assign Site Shipping', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'f_IEM_CoItemUpdateOrderQty' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'f_IEM_CoItemUpdateOrderQty', N'Update CO Line Qty', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'f_IEM_CoItemUpdateOrderQtySp' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'f_IEM_CoItemUpdateOrderQtySp', N'Update Order Line Qty', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'f_IEM_JobConfigImport' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'f_IEM_JobConfigImport', N'IEM Job Config Import', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'f_IEM_JobMaterialRelease' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'f_IEM_JobMaterialRelease', N'IEM Job Material Release', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'f_IEM_Load_Table' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'f_IEM_Load_Table', N'IEM Scheduler Load Table', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'f_IEM_Scheduler_OperationsManagement' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'f_IEM_Scheduler_OperationsManagement', N'IEM Scheduler Operations Management', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'f_IEM_Scheduler_SiteScheduler' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'f_IEM_Scheduler_SiteScheduler', N'IEM Scheduler Site Scheduler', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'f_IEM_SchedulingGroupSetup' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'f_IEM_SchedulingGroupSetup', N'IEM Scheduling Group Setup', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'f_IEM_WCScheduleView' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'f_IEM_WCScheduleView', N'_IEM WCSchedule View', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'f_MassEngineeringDrawingApprovals' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'f_MassEngineeringDrawingApprovals', N'Mass Engineering Drawing Approvals', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fAccountsReceivableAgingReport(IEM)' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fAccountsReceivableAgingReport(IEM)', N'Accounts Receivable Aging Report (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fBookingsReport (IEM)' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fBookingsReport (IEM)', N'Bookings Report (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fCustomerStatementsReport (IEM)' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fCustomerStatementsReport (IEM)', N'Customer Statements Report (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fDatabaseAudit' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fDatabaseAudit', N'Database Audit', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fIEMCombinedTransferOrderShip/Ship_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fIEMCombinedTransferOrderShip/Ship_IEM', N'IEM Combined Transfer Order Ship/Ship', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fImportCurrencyConversion_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fImportCurrencyConversion_IEM', N'Import Currency Conversion', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fJobMaterialChange_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fJobMaterialChange_IEM', N'IEM Job Material Change', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fJobOrderReceiptProcess_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fJobOrderReceiptProcess_IEM', N'Job Order Receipt Process', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fJobPickList (IEM)' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fJobPickList (IEM)', N'Job Pick List (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fJobRelease_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fJobRelease_IEM', N'IEM Job Release ', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fOrderAcknowledgmentReport' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fOrderAcknowledgmentReport', N'Order Acknowledgment Report (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fOrderInvoicingCM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fOrderInvoicingCM', N'Order Invoicing/Credit Memo (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fPurchaseOrderReportIEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fPurchaseOrderReportIEM', N'Purchase Order Report (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fReferenceDate(Optional)' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fReferenceDate(Optional)', N'Reference Date (Optional)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fReportType' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fReportType', N'Report Type', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fSalesByProductType' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fSalesByProductType', N'Sales By Product Type', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fSalesTaxReportIEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fSalesTaxReportIEM', N'Sales Tax Report (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fShippingReport' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fShippingReport', N'Shipping Report', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fStartingDate' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fStartingDate', N'Starting Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fTaxCollectedOnSales' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fTaxCollectedOnSales', N'Tax Collected On Sales (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fTaxPaidOnPurchases' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fTaxPaidOnPurchases', N'Tax Paid On Purchases (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'Include Orders Shipped Complete' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'Include Orders Shipped Complete', N'Include Orders Shipped Complete', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'Include Shipped' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'Include Shipped', N'Include Shipped', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'IncludePrice' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'IncludePrice', N'Include Price', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'm%LIsOutofRange' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'm%LIsOutofRange', N'Date Is Out of Range', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'mInvoiceReprintExcess' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'mInvoiceReprintExcess', N'~LIT~(No more than ten (10) invoices may be reprinted at one time. Please change selection and retry.)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'mIsNotAValid' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'mIsNotAValid', N'%V is not a valid %L', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'mQ=CmdQueryNoYes' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'mQ=CmdQueryNoYes', N'ARE YOU SURE? Query will be permanently deleted and all permissions and subscriptions will be lost. THIS ACTION CANNOT BE UNDONE!^Cancel|OK', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'mQ=CommMult_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'mQ=CommMult_IEM', N'The Commission Multipliers are Greater then 1.  Continue Save?^Yes|No', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'mQ=DeleteLinkedTOLineYesNo_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'mQ=DeleteLinkedTOLineYesNo_IEM', N'Delete the cross-referenced Transfer Order Line (%1) - (%2) upon save?^Yes|No', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'mQ=PoCostLessThanVendorMinYesNo_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'mQ=PoCostLessThanVendorMinYesNo_IEM', N'The PO Total (%1) is less than the Vendor Minimum PO Amount (%2). Do you want to continue?^Yes|No', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'mQ=UpdateLinesYesNo_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'mQ=UpdateLinesYesNo_IEM', N'Update Lines for Orders Moved to "Ordered"?^Yes|No', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'mW=ChangeVendorHasMinOk_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'mW=ChangeVendorHasMinOk_IEM', N'Vendor: (%1) Has A Minimum PO Amount Of (%2).  The Current PO is Below the Minimum.  The PO status cannot be updated to Planned. ^Ok', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'mW=PoCostLessThanVendorMinOk_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'mW=PoCostLessThanVendorMinOk_IEM', N'The PO Total (%1) is less than the Vendor Minimum PO Amount (%2).^Ok', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'mW=VendorHasMinOk_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'mW=VendorHasMinOk_IEM', N'Vendor: (%1) Has A Minimum PO Amount Of (%2).  The Status will be left as "Planned" until manually changed. ^Ok', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'PleaseWork' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'PleaseWork', N'Please Work', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'Queries (IEM)' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'Queries (IEM)', N'Queries (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'Resale Certificate' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'Resale Certificate', N'Resale  Certificate', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sAdd/DelQty_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sAdd/DelQty_IEM', N'Add/Del Qty', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sAge/Days' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sAge/Days', N'Age/Days', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sAge/Hrs' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sAge/Hrs', N'Age/Hrs', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sAge/Mins' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sAge/Mins', N'Age/Mins', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sAssemblyStartDate_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sAssemblyStartDate_IEM', N'Assembly Start Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sAssignSite_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sAssignSite_IEM', N'Assign Site', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sBin_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sBin_IEM', N'Bin', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sBucket_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sBucket_IEM', N'Bucket', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sBulk_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sBulk_IEM', N'Bulk', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sCareOf_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sCareOf_IEM', N'Care Of', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sChangeCompleteStatus_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sChangeCompleteStatus_IEM', N'Change Complete Status', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sChangeOperations_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sChangeOperations_IEM', N'Change Operations', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sCommissionMultiplier_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sCommissionMultiplier_IEM', N'Commission Multiplier', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sCommissionMultiplier1_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sCommissionMultiplier1_IEM', N'Commission Multiplier 1', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sCommissionMultiplier2_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sCommissionMultiplier2_IEM', N'Commission Multiplier 2', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sCommissionMultiplier3_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sCommissionMultiplier3_IEM', N'Commission Multiplier 3', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sCommissionMultiplier4_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sCommissionMultiplier4_IEM', N'Commission Multiplier 4', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sConcurrentGroups_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sConcurrentGroups_IEM', N'Concurrent Groups', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sConcurrentID_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sConcurrentID_IEM', N'Concurrent ID', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sCoQtyRemaining_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sCoQtyRemaining_IEM', N'Co Qty Remaining', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sCoShipSite_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sCoShipSite_IEM', N'Co Ship Site', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sCreateSessionDateIEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sCreateSessionDateIEM', N'Create Session Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sCustomerRequestedShipDate_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sCustomerRequestedShipDate_IEM', N'Customer Requested Ship Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sDay/Week/Month_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sDay/Week/Month_IEM', N'Day/ Week/ Month', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sDB_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sDB_IEM', N'DB Name', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sDefaultMaterialCushion_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sDefaultMaterialCushion_IEM', N'Default Material Cushion', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sDeselectAll' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sDeselectAll', N'&Deselect All', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sDoNotAddFreightAtTimeOfShipment_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sDoNotAddFreightAtTimeOfShipment_IEM', N'Do Not Add Freight At Time Of Shipment', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sEst/ActHrs_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sEst/ActHrs_IEM', N'Est/Act Hrs', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sEstimateOperationScheduled_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sEstimateOperationScheduled_IEM', N'Estimate Operation Scheduled', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sExcel' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sExcel', N'Excel', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sExpandAllProductTypes' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sExpandAllProductTypes', N' Show Individual Lines', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sFirstOpSubOp_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sFirstOpSubOp_IEM', N'First Op Sub Op', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sFreightAllowed_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sFreightAllowed_IEM', N'Freight Allowed', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sGroupMechanical_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sGroupMechanical_IEM', N'Group Mechanical', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sHardware_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sHardware_IEM', N'Hardware', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sHours/PlannedPersonnel_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sHours/PlannedPersonnel_IEM', N'Hours/ Planned Personnel', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sHrsThreshold_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sHrsThreshold_IEM', N'Hrs Threshold', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEM_AssignSite' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEM_AssignSite', N'Assign Site', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEM_ContactEmail' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEM_ContactEmail', N'Contact Email', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEM_ImportLabor' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEM_ImportLabor', N'Import Labor', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEM_ImportQuote' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEM_ImportQuote', N'Import Quote', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEM_PerformEquoteWriteBacks' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEM_PerformEquoteWriteBacks', N'Perform Equote Write Backs?', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEMCustom_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEMCustom_IEM', N'IEM Custom', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEMCustomParms_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEMCustomParms_IEM', N'IEM Custom Parms', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEMDrawApprDate' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEMDrawApprDate', N'Drawing Appr Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEMEngLeadTime' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEMEngLeadTime', N'Eng Lead Time', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEMEngSubmittal' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEMEngSubmittal', N'Eng Submittal', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEMImportFisiMaterial' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEMImportFisiMaterial', N'Import FISI Material', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEMJobName' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEMJobName', N'Job Name', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEMProdLeadTime' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEMProdLeadTime', N'Prod Lead Time', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIEMSchedLoadComplete_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIEMSchedLoadComplete_IEM', N'IEM Schedule Load Complete', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIncludeComplete_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIncludeComplete_IEM', N'Include Complete', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIncludeShipped' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIncludeShipped', N'Include Shipped', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sIneligibleCustomer_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sIneligibleCustomer_IEM', N'Ineligible Customer', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sInternalUseOnly' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sInternalUseOnly', N'Internal Use Only', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sJobReleaseAutomation_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sJobReleaseAutomation_IEM', N'Job Release Automation', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sLastSubOp_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sLastSubOp_IEM', N'Last Sub Op', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sLastUseSessionDateIEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sLastUseSessionDateIEM', N'Last Use Session Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sLinesExist_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sLinesExist_IEM', N'Lines Exist', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sLoadComplete_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sLoadComplete_IEM', N'Load Complete', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sLoadDays_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sLoadDays_IEM', N'Load Days', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sLoadNewJobs_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sLoadNewJobs_IEM', N'Load New Jobs', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sMaterialCushionDays_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sMaterialCushionDays_IEM', N'Material Cushion Days', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sMechanicalActHrs_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sMechanicalActHrs_IEM', N'Mechanical Act Hrs', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sMechanicalGroup_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sMechanicalGroup_IEM', N'Mechanical Group', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sMechanicalSubTotal_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sMechanicalSubTotal_IEM', N'Mechanical Sub Total', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sMechNumWorkers_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sMechNumWorkers_IEM', N'Mech Num Workers', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sMFGMatlType_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sMFGMatlType_IEM', N'Mfg Matl Type', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sMfgTypeSite_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sMfgTypeSite_IEM', N'Mfg Type Site', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sMinimumPOAmount_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sMinimumPOAmount_IEM', N'Minimum PO Amount', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sNewSiteAssignment_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sNewSiteAssignment_IEM', N'New Site Assignment', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sNumEmployees_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sNumEmployees_IEM', N'Num Employees', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sNumWorkers_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sNumWorkers_IEM', N'Num Workers', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sOrderAcknowledgment' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sOrderAcknowledgment', N'Order Acknowledgment', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sOrderVerificationTemplateType=4' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sOrderVerificationTemplateType=4', N'Order Acknowledgment', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sOverPct_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sOverPct_IEM', N'Over Pct', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sOverrideCode_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sOverrideCode_IEM', N'Override Code', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'SOVTemplate' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'SOVTemplate', N'Template', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sPageBetweenSuffixes' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sPageBetweenSuffixes', N'Page Between Suffixes', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sPrint' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sPrint', N'Print', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sPrintJobName' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sPrintJobName', N'Print Job Name', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sPrintLinePrice' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sPrintLinePrice', N'Print Line Price', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sPrintPrice' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sPrintPrice', N'Print Price', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sPRMA_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sPRMA_IEM', N'PRMA', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sProcessAndPack_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sProcessAndPack_IEM', N'Process And Pack', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sPromisedShipDate_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sPromisedShipDate_IEM', N'Promised Ship Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sRecordedMarginAllocation_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sRecordedMarginAllocation_IEM', N'Recorded Margin Allocation', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sReprintPackSlip_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sReprintPackSlip_IEM', N'Reprint Pack Slip', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sRequestedSubassemblyArrivalDate_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sRequestedSubassemblyArrivalDate_IEM', N'Requested Subassembly Arrival Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sResaleCertificate_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sResaleCertificate_IEM', N'Resale Certificates', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sRevenueAllocation_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sRevenueAllocation_IEM', N'Revenue Allocation', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSalesperson2_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSalesperson2_IEM', N'Salesperson 2', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSalesperson3_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSalesperson3_IEM', N'Salesperson 3', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSalesperson4_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSalesperson4_IEM', N'Salesperson 4', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSalesTaxReportTemplate' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSalesTaxReportTemplate', N'Sales Tax Report Template', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSalesTaxTemplateType=1' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSalesTaxTemplateType=1', N'Standard', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSalesTaxTemplateType=2' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSalesTaxTemplateType=2', N'Detail', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSchedGroup_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSchedGroup_IEM', N'Sched Group', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sScheduledShipDate' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sScheduledShipDate', N'Scheduled Ship Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sScheduleHoursMatrix_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sScheduleHoursMatrix_IEM', N'Schedule Hours Matrix', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSchedulerTemplate_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSchedulerTemplate_IEM', N'Scheduler Template', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSchEmployees_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSchEmployees_IEM', N'Sch Employees', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSchFinalShipDate_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSchFinalShipDate_IEM', N'Sch Final Ship Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSchLoadThresholds_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSchLoadThresholds_IEM', N'Sch Load Thresholds', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSchSubAssemblyShipDate_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSchSubAssemblyShipDate_IEM', N'Sch Sub Assembly Ship Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSelect' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSelect', N'Select', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSelectOrphanedSessionsIEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSelectOrphanedSessionsIEM', N'Select Orphaned and Day old Sessions', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sShipAndPack_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sShipAndPack_IEM', N'Ship And Pack', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sShowInvoiceDetails' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sShowInvoiceDetails', N'Include Shipped', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sShowSystemUsers' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sShowSystemUsers', N'Show System Users', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSiteAssignment_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSiteAssignment_IEM', N'Site Assign', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSiteConnectionSessions_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSiteConnectionSessions_IEM', N'Site Connection Sessions (IEM)', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSubassemblyAssignment_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSubassemblyAssignment_IEM', N'Subassy Assign', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSubAssemblyTransitTime_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSubAssemblyTransitTime_IEM', N'Sub Assembly Transit Time', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sSubOp_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sSubOp_IEM', N'Sub Op', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'Starting Date' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'Starting Date', N'Starting Date', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'StartingDateIsOutOfRange' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'StartingDateIsOutOfRange', N'Starting Date Is Out Of Range', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sTemplateType=4' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sTemplateType=4', N'Streamlined', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sTransferQtyReceived_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sTransferQtyReceived_IEM', N'Transfer Qty Received', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sTransferQtyReq_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sTransferQtyReq_IEM', N'Transfer Qty Req', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sTransferQtyShipped_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sTransferQtyShipped_IEM', N'Transfer Qty Shipped', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sUnderPct_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sUnderPct_IEM', N'Under Pct', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sWC/NumEmployees_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sWC/NumEmployees_IEM', N'WC/Num Employees', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sWorkdayHours_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sWorkdayHours_IEM', N'Workday Hours', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sWorkOrderMaterialChange_IEM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 
INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sWorkOrderMaterialChange_IEM', N'Work Order Material Change', NULL, NULL, 1, N'[NULL]', NULL)
